### ISSUE TITLE
Change of LLaTA

### ISSUE THREAD

**Issue by Hank0626** [BennyTMT/TS_Models#1]
Hi, I am the author of "LLaTA". Recently, we have changed the title of our paper to "CALF: Aligning LLMs for Time Series Forecasting via Cross-modal Fine-Tuning" and adjusted the code in the original repo. Could you please update the paper title and corresponding code in your next release?

**Comment by BennyTMT** [comment]
Hi Peiyuan,

Thanks for your reaching out, we will update to your recent version in our next releasing.

-Mingtian
________________________________
From: Peiyuan Liu ***@***.***>
Sent: Saturday, June 29, 2024 10:44 AM
To: BennyTMT/TS_Models ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BennyTMT/TS_Models] Change of LLaTA (Issue #1)


Hi, I am the author of "LLaTA". Recently, we have changed the title of our paper to "CALF: Aligning LLMs for Time Series Forecasting via Cross-modal Fine-Tuning" and adjusted the code in the original repo. Could you please update the paper title and corresponding code in your next release?

**Comment by Hank0626** [comment]
Tks!
